name: jukebox

networks:
  backend-frontend:
    driver: bridge

volumes:
  jukebox-data:
  jukebox-logs:
  musicgpt-musics:
  musicgpt-storage:

services:
  backend:
    image: jukebox-backend
    build:
      context: .
      dockerfile: Containerfile
    environment:
      - MUSIC_GENERATOR_URL=http://musicgpt:5556
    networks:
      - backend-frontend
    volumes:
      - jukebox-data:/home/jukebox/.jukebox/db/:rw
      - jukebox-logs:/home/jukebox/.jukebox/logs/:rw
    ports:
      - 3000:3000/tcp

  proxy:
    image: nginx:alpine
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
    networks:
      - backend-frontend
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro,Z
      - ./frontend/dist/:/opt/jukebox/:ro,Z
      - ./secret/:/etc/nginx/ssl:ro,Z

  musicgpt:
    image: musicgpt
    build:
      context: ./deploy/containers/music-generator
      dockerfile: Containerfile
    volumes:
      - musicgpt-storage:/root/.local/share/musicgpt/:rw
      - musicgpt-musics:/opt/musicgpt/generated:rw
    networks:
      - backend-frontend

  broadcast:
    image: jukebox-broadcast
    build:
      context: ./deploy/containers/broadcast
      dockerfile: Containerfile
    networks:
      - backend-frontend
    volumes:
      - musicgpt-musics:/opt/musicgpt/generated:rw
    ports:
      - 3001:3001/tcp
