FROM alpine

RUN apk update && \
  apk upgrade && \
  apk add --no-cache ffmpeg icecast && \
  rm -rf /var/cache/apk/*

COPY --chmod=644 ./icecast.xml /etc/icecast.xml
COPY --chmod=644 ./test.m4a /test.m4a
COPY --chmod=755 ./docker-entrypoint.sh /docker-entrypoint.sh

USER icecast

EXPOSE 3001

CMD ["/docker-entrypoint.sh"]
