FROM debian:latest

WORKDIR /opt/jukebox

RUN apt update && \
    apt upgrade && \
    apt install -y pip gcc ffmpeg && \
    pip install --break-system-packages acids-rave

# Warning, this image is humongous and is used just to TRAIN the model, not to run it
# The model is trained in a separate container and the weights are copied to the runtime container
# The runtime container is much smaller (thank god)
