name: go-test
on: [push, pull_request]
jobs:
  gotestsum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest && go mod tidy

      - name: Run tests
        run: gotestsum --junitfile gotestsum.xml ./...
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: gotestsum-results
          path: gotestsum.xml
